language: node_js
node_js:
  - '4.4'
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - "./scripts/ci.sh && ./scripts/deploy-site.sh"
before_deploy:
  - "./scripts/prepare-github-release.sh"
deploy:
  provider: releases
  api_key:
    secure: miycaOu6M7KNQHmn/AVD0r+4CMZj0ZLZTD7zicEOBqeuNV3VTIh5zjjhMTfzqDqs2/zf2vZEW+7bGSzOygaQOuyhGIH0GcgtkRitAiqax2DkbAbz+/uSxvBZbXXVbSB1FYXpVNciIWlUmkazYondqiPXbyUm4H7Vnjjh4ifNQGmzrTQwcoEOdQKnbY3JiWQyoSnbZIbTdPd8vhprjlurSkSz95jKqQPUwkUjgKydVqHRQuYBTHEoawTCObPW/XUcgKqxlh1ZJ4X+kcAzkgJ6xaySYPalCr9Qz7HMgSxs5ZmHw2ooPAZQia6YtyObH4EuxO1M1qKk0coBrjGCWfz6coXZ496aA6f2NzD+QSTwBGMCwPF7tS3G0VtnT802n7VLd5yPsHpb5rH1hsIagj+YHc4DHRrMzk7cQUgy4j2M/3t8CySI5JZvwkMd+WCNvpK51o2PZfTTY30dC/6/v8g9z3yHCJUeVDWYPzmbAxi+kdgjRasvwMk3feEUfEO842g/rvNDPIsqb22TxjaJwlXCMt4g53jkqcrHvhfOND9N29qqTq9GZ+r0eCWSBk7LQn7VrUlVNVUi2+MOe5PrZfMPueSFBpmdkaBcliivkiEan/i3Ibh+xPWkCwCm9v14OJ/IAaIwJk/Z8BTWPxoTagcNWILpIwjEdB2ddMIODyX3Frk=
  file:
    - github-release-assets/dist.zip
    - github-release-assets/dist.tar.gz
  skip_cleanup: true
  on:
    repo: ScottLogic/BitFlux
    tags: true
notifications:
  slack:
    secure: thS2DH2l15+QD9MffNQX41PD3nEig8NsiHGbjWyS22n4P1MYkkoAFTqHnhZnzPHe/gYBlOMPxrQCC/WzAFJ0MIXK1CXNm37JALTL6YCc9hlOTQIOXdKM7Ql7nmeNx9eeK8qrHBN0WQqUwKAtdMeFubHBZkpLCeh2ifPw0hNrEe6bAfYdLap/32m0zgr+2UF2KiljXjyvKktLLpRhJ0BAH2HHRIA8KnssN3suwNl/RKJ45ipcagxgEEF0mrZlPOsWYDVNCRj23bQDO1P5PaUlgrzo0zDOflfa8aIqJaqvB505E9cGzhV5TNtehHJt38LOt85ErSX9cejaVUpaS155+YLsWJpQzmt8I3m47DDnmFCEja2toszTga2fhopnPguulSt6b8zSP2SyOmSWawqO7RNLoV2hFpdU+Mw2BL62stuyAoTGfYya+Qw5y2Sd4cRY7hZJS6mFaSGKOKeRVndSeqEyHa8j9CpYkrHDTht6NbNRzPOWuYiVSwYNGX67dab3ApiQRUH+Rf8ubAyyuJKkUrUm5s/zaXyHoWhe0azYIPHBOtHh4e0BMda8kJNpDO7MTSv9WCIpRbk7Jb6vGrPrUIkyAel2DaCaO0UzzLMv6jjvXeYqZTW6K+CIRo6V4Rqj7odhMLvi1DlLaf0fjGoJIScP7/xKVpzYRyRt+DNx9OU=
env:
  global:
  - GH_REF: github.com/ScottLogic/BitFlux.git
  - secure: YSvDn5LuTWE1ZqRtB3woUlrEtssLx4RAy8DpSChzrnBf5q4zV/AnSxfdtsqu0QqP7lpN6ZDz9A0sGKxEPT7MWQQ/YtzwR7CSlOIWulIPihMCw6yAkuDHwR4kSJaPvgWFEUPYZ8Mp7SVfWjxqexMJ0SGF+q/WCr976s+NHPMMhiAQgMfaauxSDnadvknS1mCEkCxFIPxTDl3mDqWMeVUJ5oY+bc5fOqVfOlwZ8zogm84FqbvdCQYfyeL6Aj7Yx96Szo23yEuDTdp9bNJFVXp63m6EmBC/+SG/3W+iKQXqkgmocf62mSaxnNA4e3eC5RWb1V3fRKyIVYDq//Jx/Nrx4NFYdad3Y8fS/i7V+gUAzpyKCZTb8CRu7fMqc763LHnZ7378e5ouPQvnPixe9SIAjsIBzex/yJzC94E7W2nI2g+c/FTUELl2qmvL2D2dGqzPRHg4FqIIrxZe7TlvrXpHc699w16OIcy0CckUdJFOFT41yx09SLQuQSbjzROdEY4QyJgJiHBQT0hp0s3EEghDLle9qjofFPbxN84CZsYvWjxSXaS9e0y+QmJupo88m6gtgjAYnZnogRxbRoqkvAz8X0ib15ZTeT7kOnHnCpEiDFj5Zos+kzeZgdxTlf3nj+1LkQXT53BGzgRMdUE8CSpE58855aqQ7wza78p+cA4n72w=
